name: Build Windows EXE

on:
  workflow_dispatch:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: windows-latest
    steps:
      - name: Check out
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install deps
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install requests
          pip install pyinstaller

      - name: Build exe
        run: |
          pyinstaller racing_gui.py --onedir --noconsole --name MoneyMaker --icon=icon.ico

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: MyApp-windows-x64
          path: dist/**
